Improve the component styling
kumojin/vue-money-amount pull request #17
Opened 2020-10-26 21:26 UTC by meliecool

resolves #3

2020-10-26 21:34 UTC, lunatetzuka commented on .storybook/main.js
> +          },
```suggestion
          { loader: 'sass-loader' },
```

2020-10-26 21:34 UTC, lunatetzuka commented on package.json
> +    "css-loader": "^5.0.0",
move to devDependencies

2020-10-26 21:34 UTC, lunatetzuka commented on package.json
> +    "sass-loader": "^10.0.4",
move to devDependencies

2020-10-26 21:34 UTC, lunatetzuka commented on package.json
> +    "@storybook/addon-actions": "^5.3.19",
to remove ?

2020-10-26 21:34 UTC, lunatetzuka commented on src/MoneyAmount.vue
> +      }
```suggestion
     return this.amount > 0
       ? 'money-amount--positive'
       : this.amount < 0
         ? 'money-amount--negative'
         : 'money-amount--zero';
```

2020-10-26 21:41 UTC, meliecool commented
Ok! I add the colors optional + change dependencies to dev

2020-10-26 21:49 UTC, meliecool commented on src/MoneyAmount.vue
> +      }
The lint is too severe for that

2020-10-27 00:15 UTC, LukaszKokot requested changes
I don't want any colors by default, as the CSS will inevitably vary from a project to another. I would just like the CSS classes to be added though.
So having `money-amount--positive` or `money-amount--negative` or `money-amount--zero` is perfect, but no styling please.
If you want, you can however configure your storybook stories so that the amounts are styled, to demonstrate that it works!

2020-10-27 00:15 UTC, LukaszKokot commented on src/MoneyAmount.vue
> +    hasColors: {
Please remove this property.

2020-10-27 00:16 UTC, LukaszKokot commented on src/MoneyAmount.vue
> +<style lang="scss">
Please remove the styling

2020-10-27 13:12 UTC, meliecool commented on src/MoneyAmount.vue
> +    hasColors: {
It's done

2020-10-27 13:12 UTC, meliecool commented on src/MoneyAmount.vue
> +<style lang="scss">
It's done too

2020-10-27 13:32 UTC, lunatetzuka commented on .storybook/preview-body.html
> +  .money-amountnegative {
```suggestion
  .money-amount--negative {
```

2020-10-27 13:43 UTC, LukaszKokot approved these changes
If you fix @lunatetzuka  's comment, it's good!

2020-10-27 13:46 UTC, lunatetzuka approved these changes

2020-10-27 13:47 UTC, merged